### ISSUE TITLE
missing pre tag with language-* class

### ISSUE THREAD

**Issue by mariusespejo** [timlrx/rehype-prism-plus#14]
hey there! First of all great work on the plugin.

One issue that I've noticed is that this isn't actually compatible with most prism theme styles out of the box because it doesn't generate a `pre` tag with the `language-` class copied over.

Context from similar `rehype-prism`'s FAQ: https://github.com/mapbox/rehype-prism#faq

As a clear example if you look at any typical theme css for prism, [like NightOwl](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-night-owl.css) as given example in the README,  you'll notice that most of the CSS have the following as selectors (to apply styles to the actual code block, relying on prismJS behavior): 

```css
pre[class*="language-"] { }
```

In the README you have:
> To style the language tokens, you can just copy them from any prismjs compatible ones. Here's a list of themes.

Which does style the tokens, but not the greater code block, which the screenshot provided makes you assume also happens. 

I could be wrong but looking at your usage of this plugin in [`tailwind-nextjs-starter-blog`](https://github.com/timlrx/tailwind-nextjs-starter-blog) it seems as if the code block styles are dependent on your use of the `prose` class from [`@tailwindcss/typography`](https://github.com/tailwindlabs/tailwindcss-typography#readme), making this plugin not really as usable on it's own.

Perhaps there is missing documentation that could be added to call that out? Or maybe an option added so that you can toggle to add the `language-` class to the `pre` tag?

Thoughts? thanks.

**Comment by timlrx** [comment]
Yes, you are right. You can adapt the token classes from the compatible prism stylesheets but would still need to style the code block itself or modify the `pre` to target `code` instead. Will add a clarification in the readme.

I am open to adding back the `language-` class to the `pre` tag and add it as an option. Happy to accept a PR if somebody would like to make that change.
