### ISSUE TITLE
Code moves when line number goes from 9 to 10

### ISSUE THREAD

**Issue by einoken** [timlrx/rehype-prism-plus#17]
Hi. Thank you for an awesome plugin.

I noticed that when the line number goes from an n-digit number to an n+1-digit number, the position of the code shifts to the right as well. It is more noticeable with unindented lines of code (red line added for emphasis).

## Current
![alignment](https://user-images.githubusercontent.com/36775736/139708196-ba66975b-5ae1-45b1-9895-ed41af003051.png)

## Expected
It should probably look something like this.
![alignment_2](https://user-images.githubusercontent.com/36775736/139708236-e79e20ad-902a-40b6-b499-b5e8d3416761.png)

**Comment by timlrx** [comment]
Thanks, a fix is suggested in my other repo: https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/267

The css style for line-number should be right-aligned.

Let me know if something like this works and I will update the readme code:

```
.line-number::before {
  display: inline-block;
  width: 1rem;
  text-align: right;
  margin-right: 16px;
  margin-left: -8px;
  color: rgb(156, 163, 175); /* Line number color */
  content: attr(line);
}
```

**Comment by einoken** [comment]
> Thanks, a fix is suggested in my other repo: [timlrx/tailwind-nextjs-starter-blog#267](https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/267)
> 
> The css style for line-number should be right-aligned.
> 
> Let me know if something like this works and I will update the readme code:
> 
> ```
> .line-number::before {
>   display: inline-block;
>   width: 1rem;
>   text-align: right;
>   margin-right: 16px;
>   margin-left: -8px;
>   color: rgb(156, 163, 175); /* Line number color */
>   content: attr(line);
> }
> ```

Yes, this fixed the issue. Thank you very much!

**Comment by timlrx** [comment]
Updated readme with the fix, thanks!

**Comment by vidhanio** [comment]
For me, it was most importantly the `width: <number>rem;` along with the `text-align: right`. If the width was not manually set, it would just be the size of the number, not moving it at all.
