### ISSUE TITLE
Unable to compile TypeScript file that imports the module due to missing/ incorrect type

### ISSUE THREAD

**Issue by motss** [timlrx/rehype-prism-plus#23]
## Problem

This is the error message when compiling TypeScript file that imports the module.

```sh
error TS2315: Type 'Visitor' is not generic.

9 export type Visitor = import('unist-util-visit').Visitor<Node>;
```

## Reduced test case

This is a reduced test case written in TypeScript

```ts
import rehypePrism from 'rehype-prism-plus';
import rehypeStringify from 'rehype-stringify';
import remarkGfm from 'remark-gfm';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { unified } from 'unified';
import type { VFile } from 'vfile';

export async function mdParse(value: string): Promise<VFile> {
  return unified()
    // remark
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    // rehype
    .use(rehypePrism)
    .use(rehypeStringify)
    .process(value);
}
```

## Expected behavior

TypeScript file that imports the module should compile successfully without any typing issue

## Actual behavior

TypeScript file fails to compile due to missing/ incorrect type

## Other information

1. TypeScript: 4.5.4
2. vite: 2.7.2
3. vue-tsc: 0.30.2
3. rehype-prism-plus: 1.1.3

**Comment by timlrx** [comment]
I replicated the code with all the latest versions of the dependencies and typescript 4.5.4 and have no issue.

I got a feeling that there is some kind of module resolution problem going on. Can you try running `npm ls unist-util-visit` and see whether there are any dependencies on versions <3? Most of the google searches for `error TS2315` suggest deleting `node_modules`, `package-lock.json` and installing again.

**Comment by motss** [comment]
@timlrx Tested again with the suggestion in your previous comment but still having the same problem.

AFAIK it is not a TypeScript problem. Please try this [repo](https://github.com/motss/rehype-prism-plus-typing-issue) and it is easily reproducible.

**Comment by timlrx** [comment]
I removed that line and published a new package. It should work now.

**Comment by motss** [comment]
@timlrx I think you haven't published a new version because that line was removed after v1.2.0.

**Comment by timlrx** [comment]
It was published on npm. Also published the release on Github now.
