### ISSUE TITLE
Wrapping code snippets in a `div` puts the code title at a wrong position

### ISSUE THREAD

**Issue by AlexanderZeilmann** [timlrx/rehype-prism-plus#29]
In a standard setup of Tailwind Nextjs Starter Blog I want to write a blog post that includes a very long code snippet.
My idea was to wrap it in a `div` as follows:

    <div style={{height: '300px', overflow: 'scroll'}}>
    ```json:fileName.json
    A very long code snippet
    ```
    </div>

However, this generates the problem that the code title, i.e., the bar with the name of the file, will be placed at the beginning of the entire blog post and not directly above the code snippet.

A workaround might be to define a `max-height` for all code snippets, but I would like to have this customizable for each code block.

**Comment by timlrx** [comment]
To specify the `max-height` for all code elements, I think adding a CSS property would be the best way. To customize for each code block, your way of doing it is good.

**Comment by hinsxd** [comment]
is it possible to add a new config/let user extend the config to specific the max-height (or completely change the dom node)?

**Comment by timlrx** [comment]
> is it possible to add a new config/let user extend the config to specific the max-height (or completely change the dom node)?

@hinsxd how about just adding the `max-height` CSS property as required. After all, the other styling options are also done via an external stylesheet. Are you facing any limitations with this approach?

**Comment by talatkuyuk** [comment]
**In order to put the code title and the code block in a div container**, you can check the **new package** [remark-flexible-code-titles](https://www.npmjs.com/package/remark-flexible-code-titles). 

It also offers custom className for the container. You can play with the `CSS` having the className. **You don't need to put the code inside a div yourself.**
