### ISSUE TITLE
Parser adding extra `<span>` to toml properties

### ISSUE THREAD

**Issue by edwincoronado** [timlrx/rehype-prism-plus#31]
I have a code snippet written in TOML. The parser is adding an extra span to the name of the property and causing a line break:

<img width="205" alt="Screen Shot 2022-02-04 at 8 08 55 PM" src="https://user-images.githubusercontent.com/7434954/152628175-3f677694-c6e0-4b2d-88ef-3c5672c7a448.png">
<img width="442" alt="Screen Shot 2022-02-04 at 8 09 06 PM" src="https://user-images.githubusercontent.com/7434954/152628177-7708fbae-7df7-407b-952b-938bf8dcb2ba.png">

`refactor` doesn't do the same, you can see a sample of output here: https://replit.com/@edwincoronado/official-refractor-demo#index.js

**Comment by timlrx** [comment]
It does, in your repl, you are parsing it wrongly with js instead of toml. In any case, the span should not cause a line break and it should be some CSS setting that is misconfigured.

**Comment by timlrx** [comment]
Here's the output I get from refractor:

```
<span class="token punctuation">[</span><span class="token table class-name">teo</span><span class="token punctuation">]</span>
```

I guess you are using my template or another tailwind template? The line break is caused by the `table` class. Tailwind uses this class to insert `display: table`. To fix this problem, you could just insert a line in your prism stylesheet like so

```
.token.table {
  display: inline;
}
```

**Comment by edwincoronado** [comment]
thanks! that worked.
