### ISSUE TITLE
Easiest or recommended method to add a copy code button

### ISSUE THREAD

**Issue by jannikbuscha** [timlrx/rehype-prism-plus#32]
Hi, I was wondering what is the easiest or recommended method to add a copy code button, like in the github markdown view.

**Comment by AlexanderZeilmann** [comment]
Have a look [here](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/359f82b1497772bc3c5d43ff1c612e01268699b2/components/Pre.js) for an implementation of this feature in the context of an mdx based blog 🙂

**Comment by jannikbuscha** [comment]
yes i have now started to write my own rehype plugin, this was also recommended to me in the mdx discussion.

**Comment by harryhan24** [comment]
@AlexanderZeilmann i think it is easiest way to add copy button. thanks.
