### ISSUE TITLE
How to disable showLineNumbers on a per block basis

### ISSUE THREAD

**Issue by CanRau** [timlrx/rehype-prism-plus#38]
Hi there ☺️

I enabled `showLineNumbers` in the plugin's settings, so they're always enabled, how can I disable line numbers on a specific block?

I tried

```md
```toml showLineNumbers=false
```toml showLineNumbers="false"
```toml showLineNumbers={false}
```

without any luck 😬 and peeking at the code looks like it's not supported at the moment?

**Comment by timlrx** [comment]
Hi! Yes, you are right. It's not supported at the moment. Should be a relatively simple fix though and I could patch it later in the week or let me know if you want to give it a try?

**Comment by CanRau** [comment]
Too slow you've beat me 😄
