### ISSUE TITLE
deletion and insertion

### ISSUE THREAD

**Issue by Code-Victor** [timlrx/rehype-prism-plus#51]
is there a way to highlight lines that are deleted and lines that are removed?

**Comment by timlrx** [comment]
Yes, you can style the inserted lines by targeting `.code-line.inserted` and the deleted lines with `.code-line.deleted`. Currently, the `inserted` and `deleted` classes are only added if the language is `diff` ([reference code](https://github.com/timlrx/rehype-prism-plus/blob/main/src/generator.js#L278-L282)).

**Comment by Code-Victor** [comment]
alright, thanks.
I'm using MDX , is there any way to have js syntax highlight with a diff?

**Comment by timlrx** [comment]
Not at the moment because the package simply runs the list of language against https://github.com/wooorm/refractor. We could possibly detect `diff:js` as a language and run it through the diff parser, followed by the js parser to add the correct tokens. Happy to accept a PR on that.

**Comment by timlrx** [comment]
Added in #53 and published in v1.5.0. Thanks for the enhancement 👍
