### ISSUE TITLE
Default fallback language

### ISSUE THREAD

**Issue by ddoan** [timlrx/rehype-prism-plus#58]
Hi Tim, I love this plugin :)

Was wondering if you could add an option to have a default fallback language? I'd love this option vs on-the-fly modifying my markdown to inject it.

**Comment by timlrx** [comment]
Hi Doug, that's a good idea! Will look into a way to generate an instance of the plugin with a default language or expose it as an option.

**Comment by timlrx** [comment]
Released as v1.6.0! - https://github.com/timlrx/rehype-prism-plus/releases/tag/v1.6.0

**Comment by ddoan** [comment]
Thats great, thank you for the fast turnaround!!
