### ISSUE TITLE
defaultLanguage sets pre tag but not code tag

### ISSUE THREAD

**Issue by ddoan** [timlrx/rehype-prism-plus#60]
Hi Tim, I think there's a small issue with the new option. It doesn't quite produce the same result as specifying a language.

<img width="396" alt="Screenshot 2023-06-24 at 9 11 09 AM" src="https://github.com/timlrx/rehype-prism-plus/assets/993727/0af4b264-6f48-40e9-90d0-07f57742bd71">

**Comment by timlrx** [comment]
The difference is that `language-js` is not added as a class in the default code blocks? Ok, will fix it to be the same. I have tested that the syntax highlighting is the same but let me know if you see any differences.

**Comment by timlrx** [comment]
Should be fixed in the newly released 1.6.1

**Comment by ddoan** [comment]
Confirmed on my end. Thanks again
