### ISSUE TITLE
Git diff file coordinates don't always get labeled correctly

### ISSUE THREAD

**Issue by ddoan** [timlrx/rehype-prism-plus#62]
Hi Tim, I am not sure this is a problem with your plugin or some other one, but I would love it if you could point me in the right direction in any case. I'm using `diff` as the language BTW.

If I have the following:

```
diff --git a/blah.css b/blah.css
index 7b1cbad..a304d0b 100644
--- a/blah.css
+++ b/blah.css
@@ -1,11 +1,3 @@
```

Then it gets rendered as:

```
<span class="token coord">@@ -1,11 +1,3 @@</span>
```

However if I have this:

```
diff --git a/blah.tsx b/blah.tsx
index d617b6e..86dc6a3 100644
--- a/blah.tsx
+++ b/blah.tsx
@@ -152,9 +152,7 @@ export function MyFunction({
```

Then it gets rendered as:

```
<span class="code-line">@@ -152,9 +152,7 @@ export function MyFunction({
</span>
```

**Comment by timlrx** [comment]
Hi Doug, not sure what's the issue over here. `diff` only works on the lines that starts with `+` or `-` and adds an `inserted` or `deleted` class to the line. Both these two lines of code, `@@ -1,11 +1,3 @@` or `@@ -152,9 +152,7 @@ export function MyFunction({` are not affected by the diff plugin and are just treated as a normal language.

Having said that, the first line should only have a `code-line` class to it. Is that the issue? Or are you expecting something else?

**Comment by ddoan** [comment]
`@@ -1,11 +1,3 @@` does get affected and is added `"token coord"`.

I managed to workaround this issue by doing a regex replace on the output 🤷‍♂️
