### ISSUE TITLE
Can't build when moduleResolution set to bundler.

### ISSUE THREAD

**Issue by dairidong** [timlrx/rehype-prism-plus#63]
my `tsconfig.json`:
```json
{
    "compilerOptions": {
        "allowJs": true,
        "baseUrl": "./",
        "module": "ESNext",
        "moduleResolution": "bundler",
        "jsx": "react-jsx",
        "strict": true,
        "isolatedModules": true,
        "target": "ESNext",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "skipLibCheck": true,
        "paths": {
            "@/*": [
                "./resources/js/*"
            ],
            "@styles/*": [
                "./resources/css/*"
            ]
        }
    },
    "include": [
        "resources/js/**/*.ts",
        "resources/js/**/*.tsx",
        "resources/js/**/*.d.ts"
    ],
    "exclude": [
        "node_modules/*"
    ]
}
```

tsc error:
```
yarn run v1.22.19
$ tsc && vite build && vite build --ssr
resources/js/Pages/Articles/Show/index.tsx:5:25 - error TS7016: Could not find a declaration file for module 'rehype-prism-plus'. '/home/dairidong/code/react_blog/node_modules/rehype-prism-plus/dist/rehype-prism-plus.es.js' implicitly has an 'any' type.
  There are types at '/home/dairidong/code/react_blog/node_modules/rehype-prism-plus/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'rehype-prism-plus' library may need to update its package.json or typings.

5 import rehypePrism from "rehype-prism-plus";
```
it's only can run success if i set `"moduleResolution": "node"` or  `"noImplicitAny": false`

**Comment by timlrx** [comment]
Hmm not too sure about this one. Seems like it is expecting types for `rehype-prism-plus.es.js` directly as well? I might need to create a sample vite app to figure out what's the issue. Meanwhile, I think you could also workaround it by declaring the module explicitly: https://pjausovec.medium.com/how-to-fix-error-ts7016-could-not-find-a-declaration-file-for-module-xyz-has-an-any-type-ecab588800a8

**Comment by dairidong** [comment]
> Hmm not too sure about this one. Seems like it is expecting types for `rehype-prism-plus.es.js` directly as well? I might need to create a sample vite app to figure out what's the issue. Meanwhile, I think you could also workaround it by declaring the module explicitly: https://pjausovec.medium.com/how-to-fix-error-ts7016-could-not-find-a-declaration-file-for-module-xyz-has-an-any-type-ecab588800a8

Thank you, I can set the `"noImplicitAny": false` temporarily, but I want a right way to solve the problem.

I found some similar problems here https://github.com/microsoft/TypeScript/issues/52363 , hope this can help.

**Comment by timlrx** [comment]
Thanks, the link helps! Fixed the issue. Let me know if it works for you.

**Comment by dairidong** [comment]
It works now, thanks for your help!
