### ISSUE TITLE
receive custom attributes.

### ISSUE THREAD

**Issue by Flysky12138** [timlrx/rehype-prism-plus#71]
~~~
```js expanded
***
```
~~~

```tsx
export default function Pre({ children, className, ...props }: React.ComponentProps<'pre'>) {
  console.log(props)
  return null
}
```

i wanna get `expanded`

**Comment by talatkuyuk** [comment]
What do you want exactly? Why do you return `null` in pre component? Do you want to get "expanded" property in code element, or only in pre element? Can you explain what would you like to see in the output html, we need more detail, please.

**Comment by Flysky12138** [comment]
I am using `next-mdx-remote`. Like this, I want to get the 'expanded' parameter

```tsx
<MDXRemote
  components={{
    pre: function Pre({ children, className, ...props }: React.ComponentProps<'pre'>) {
      console.log(props.expanded)
      return <pre>{children}</pre>
    }
  }}
  options={{
    rehypePlugins: [rehypeKatex, rehypePrismPlus, rehypeSlug],
    remarkPlugins: [remarkGfm, remarkMath, remarkDirective, remarkDirectiveRehype]
  }}
  source="# h1"
/>
```

**Comment by timlrx** [comment]
Hi @Flysky12138 I don't see it as a feature that should be included as part of a highlighting plugin. You could consider including your own remark plugin to transform or store desired attributes.
